#Deployment do banco Postgre

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre 
          image: postgres:14.3 
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "P@ssWord25485"  #password
          - name: POSTGRES_USER
            value: "kubenews"  #database
          - name: POSTGRES_DB
            value: "kubenews"  #username
--- 
#Service do Deployment postgre
apiVersion: v1
kind: Service 
metadata:
  name: postgre
spec: 
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
# Criação do Deployment kubnews 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  kubenews  #nome da aplicação 
spec:
  replicas: 10  #qtde de pod 
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels: 
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: nandocloud/kube-new:v6  #imagem no  dockerhub
        env:        
        - name: DB_DATABASE  #acesso ao dados da aplicção banco postgre
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "P@ssWord25485"
        - name: DB_HOST
          value: "postgre"
--- 
# criação do service expomndo a porta 
apiVersion: v1
kind: Service 
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30010  #docker ps -a
  type: NodePort

